core_packages:
    - binutils
    - bash
    - base-devel
    - gcc
    - pkg-config
    - fakeroot
    - less
    - bc
    - colordiff
    - fzf
    - ripgrep
    - jq
    - rsync
    - parallel
    - pwgen
    - go
    - git
    - tig
    - sudo
    - ranger
    - vim
    - pkgfile
    - mlocate
    - make
    - bat
    - exa
    - shellcheck
    - fish
    - zsh
    - fd
    - tldr
    - z
    - yarn
    - npm
    - ntfs-3g
    - networkmanager
    - networkmanager-openvpn

main_pkg:
    - firefox
    - alacritty
    - kitty
    - vlc

utils:
    - net-tools
    - curl
    - wget
    - bind
    - nmap
    - gnu-netcat
    - whois
    - mtr
    - tcpdump
    - sshpass
    - dnsutils
    - ipcalc
    - python-pip
    - htop
    - bpytop
    - atop
    - rsync
    - aws-cli
    - traceroute
    - openvpn
    - neofetch
    - fastfetch
    - syncthing

packages:
    - gparted
    - unzip
    - bitwarden
    - steam
    - pavucontrol
    - neovim
    - deja-dup
    - qbittorrent
    - docker
    - vagrant

aur:
    - ocs-url
    - brave-bin
    - timeshift
    - timeshift-autosnap
    - waterfox-bin


flatpak:
    - com.github.tchx84.Flatseal
    - com.obsproject.Studio
    - com.spotify.Client
    - md.obsidian.Obsidian
    - org.onlyoffice.desktopeditors
    - org.nickvision.tubeconverter
    - com.getmailspring.Mailspring
    - com.visualstudio.code
    - net.davidotek.pupgui2
    - com.google.Chrome
    - com.mattjakeman.ExtensionManager
    - org.gnome.Todo
