---
gaming_packages:
  - steam
  - lutris
  - gamemode
  - wine
  - wine-mono
  - wine-gecko
  - winetricks
  - lib32-vulkan-icd-loader
  - lib32-mesa
  - vulkan-icd-loader
  - mesa

gaming_aur_packages:
  - hydra-launcher-bin

gaming_wine_prefix: "/home/{{ user.username }}/.wine"
gaming_wine_arch: "win64"
