---
- name: Ensure dotfiles directory exists
  ansible.builtin.file:
    path: "{{ user.dotfiles.path }}"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.group }}"
    mode: "0755"
  become: true

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "{{ user.dotfiles.repo }}"
    dest: "{{ user.dotfiles.path }}"
    version: "master"
    force: true
    update: true
    accept_hostkey: true
  become: true
  become_user: "{{ user.username }}"

- name: Install stow if not present
  community.general.pacman:
    name: stow
    state: present
  become: true

- name: Apply dotfiles using stow
  ansible.builtin.command:
    cmd: "stow --dotfiles --target=/home/{{ user.username }} ."
    chdir: "{{ user.dotfiles.path }}"
    creates: "/home/{{ user.username }}/.zshrc/"
  become: true
  become_user: "{{ user.username }}"
