---
- name: Configure user Git config
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "/home/{{ user.username }}/.gitconfig"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: "0644"
