env_system_vars:
  EDITOR: "nvim"
  GTK_DEFAULT_COLOR_SCHEME: "prefer-dark"
  WLR_NO_HARDWARE_CURSORS: "1"
  GBM_BACKEND: "nvidia"
  LIBVA_DRIVER_NAME: "nvidia"
  XCURSOR_THEME: "Yaru"
  XCURSOR_SIZE: "24"
  __GLX_VENDOR_LIBRARY_NAME: "nvidia"
