desktop_packages:
  hyprland:
    packages:
      # Hyprland
      - hyprland
      - blueberry
      - dconf
      - ghostty
      - grim
      - hyprlock
      - hyprshot
      - kitty
      - libnotify
      - mako
      - omarchy-walker
      - polkit-gnome
      - swaybg
      - swayosd
      - waybar
      - wofi
      - pavucontrol
      - pamixer
      - wiremix
      # Clipboard
      - cliphist
      - wl-clip-persist
      - wl-clipboard
      # Theme // Appearance
      - adwaita-fonts
      - adwaita-icon-theme
      - vimix-cursors
      - noto-fonts-emoji
      - yaru-icon-theme
      # GNOME // Nautilus
      - gnome-calculator
      - gnome-keyring
      - file-roller
      - gsettings-desktop-schemas
      - nautilus
      - sushi
      # Desktop portals
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
    display_manager: "uwsm"
  gnome:
    packages:
      - gnome
      - gdm
    display_manager: "gdm"
  kde:
    packages:
      - plasma
      - sddm
    display_manager: "sddm"
