desktop_packages:
  hyprland:
    packages:
      - hyprland
      - mako
      - dconf
    display_manager: "uwsm"
  gnome:
    packages:
      - gnome
      - gdm
    display_manager: "gdm"
  kde:
    packages:
      - plasma
      - sddm
    display_manager: "sddm"
