nvidia_nvidia:
  enable: false
  packages:
    - nvidia
    - nvidia-utils
    - lib32-nvidia-utils
    - nvidia-settings
  targets:
    - nvidia
    - linux
  env_vars:
    GBM_BACKEND: "nvidia-drm"
    LIBVA_DRIVER_NAME: "nvidia"
    __GLX_VENDOR_LIBRARY_NAME: "nvidia"
