---
- name: Enable Gamemode service
  ansible.builtin.systemd:
    name: gamemoded
    enabled: true
    state: started
    scope: user
  become: true
  become_user: "{{ user.username }}"
  tags: [gaming, gaming_optimizations]
