---
- name: Install gaming packages
  community.general.pacman:
    name: "{{ gaming_packages }}"
    state: present
  become: true

- name: Install gaming aur packages
  become: true
  become_user: "{{ user.username }}"
  kewlfft.aur.aur:
    name: "{{ gaming_aur_packages }}"
    state: present
  failed_when: false
