---
base_system_packages:
  # System
  - egl-wayland
  - imagemagick
  - less
  - sof-firmware
  # Pipewire
  - pipewire
  - pipewire-alsa
  - pipewire-audio
  - pipewire-pulse
  - gst-plugin-pipewire
  - wireplumber

base_packages_essential:
  - less
  - tree
  - man-db
  - man-pages
  - texinfo
  - bash-completion
  - which
  - file
  - findutils
  - gzip
  - tar
  - unzip
  - zip
  - rsync
  - net-tools
  - iproute2
  - openssh
  - wget
  - curl
  - socat
  - nmap
  - htop
  - strace
  - lsof
  - psmisc
  - procps-ng
  - sysstat
  - iotop
  - lsb-release
  - dosfstools
  - exfatprogs
  - ntfs-3g
  - parted
  - e2fsprogs
  - xfsprogs
  - btrfs-progs
  - sudo
  - jq
  - tzdata
  - fcitx5
  - fcitx5-gtk
  - fcitx5-qt
