---
base_system_packages:
  # System
  - egl-wayland
  - imagemagick
  - less
  - sof-firmware
  # Pipewire
  - pipewire
  - pipewire-alsa
  - pipewire-audio
  - pipewire-pulse
  - gst-plugin-pipewire
  - wireplumber
