---
base_system_packages:
  # System
  - egl-wayland
  - imagemagick
  - less
  - sof-firmware
  # Pipewire
  - pipewire
  - pipewire-alsa
  - pipewire-audio
  - pipewire-pulse
  - gst-plugin-pipewire
  - wireplumber

base_packages_essential:
  # Navegação e leitura
  - less
  - tree
  - man-db
  - man-pages
  - texinfo

  # Shell e completions
  - bash-completion

  # Utilitários base
  - which
  - file
  - findutils
  - gzip
  - tar
  - unzip
  - zip
  - rsync

  # Networking
  - net-tools
  - iproute2
  - openssh
  - wget
  - curl
  - socat
  - nmap

  # Monitoramento / Debug
  - htop
  - strace
  - lsof
  - psmisc
  - procps-ng
  - sysstat
  - iotop
  - lsb-release

  # FS e disco
  - dosfstools
  - exfatprogs
  - ntfs-3g
  - parted
  - e2fsprogs
  - xfsprogs
  - btrfs-progs

  # Outros básicos
  - sudo
  - jq
  - tzdata
