---
- name: Import pacman config tasks
  ansible.builtin.include_tasks: pacman.yml

- name: Import AUR config tasks
  ansible.builtin.include_tasks: aur.yml

- name: Import sudo config task
  ansible.builtin.include_tasks: sudo.yml

- name: Import user config task
  ansible.builtin.include_tasks: user.yml
